spring:
  threads:
    virtual: enabled
  jpa:
    show-sql: true

vaadin:
  launch-browser: true

ai:
  token: ${GEMINI_TOKEN:AIzaSyD9D3Q_ywyrvvkXO9uMAzrHD4QSha5a73s}

logging:
  level:
    org.springframework.messaging: debug
    org.springframework.web.socket: debug
    org.springframework.messaging.simp: debug
    ao.appsuportegirassol: debug
