spring:
  threads:
    virtual: enabled
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/girassol
    username: root
    password: 1234
  docker:
    compose:
      enabled: false

vaadin:
  launch-browser: true

ai:
  token: ${GEMINI_TOKEN:AIzaSyD9D3Q_ywyrvvkXO9uMAzrHD4QSha5a73s}

logging:
  level:
    org.springframework.messaging: debug
    org.springframework.web.socket: debug
    org.springframework.messaging.simp: debug
    ao.appsuportegirassol: debug
