spring:
  threads:
    virtual: enabled
  jpa:
    show-sql: true

vaadin:
  launch-browser: true

ai:
  token: ${GEMINI_TOKEN:AIzaSyBdAGqv5yIfa5BMGXFeA8qIKW0GZLCo6mg}

logging:
  level:
    org.springframework.messaging: debug
